View (Reshape) 함수

In [15]:
import numpy as np
import torch

In [16]:
t = np.array([[[0, 1, 2],
                [3, 4, 5]],
               
               [[6, 7, 8],
                [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [17]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [18]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Squeeze 함수

In [19]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [20]:
print(ft.squeeze())
print(ft.squeeze().shape)
print(ft.squeeze(dim=0))  # 첫번째 dim은 3이므로 변화 없음
print(ft.squeeze(dim=1))

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


Unsqueeze 함수

In [25]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [26]:
print(ft.unsqueeze(0))  # dim=0
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [27]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [28]:
print(ft.unsqueeze(1))  
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
print(ft.unsqueeze(-1))  # dim=-1 => dim=1
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Type Casting

In [30]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [31]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [32]:
bt = torch.ByteTensor([True, False, False, True])   # ByteTensor는 분리형 값을 저장
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [33]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


Concatenate

In [34]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [35]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


Stacking

In [38]:
x = torch.FloatTensor([1, 4])     # |x| = |y| = |z| = (2, )
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [39]:
print(torch.stack([x, y, z]))           # (3, 2)
print(torch.stack([x, y, z], dim=1))    # (2, 3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [40]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
                   # (1, 2)           (1, 2)           (1, 2) 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


Ones and Zeros

In [41]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [42]:
print(torch.ones_like(x))    # 1로 채워진 같은 shape의 텐서가 생성됨
print(torch.zeros_like(x))   # 0으로 채워진 같은 shape의 텐서가 생성됨

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In-place Operation

In [43]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [44]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
